#!/usr/bin/env python




bld.SAMBA3_MODULE('vfs_vfsx',
                 subsystem='vfs',
                 source='vfs_vfsx.c',
                 deps='',
                 init_function='',
                 internal_module=bld.SAMBA3_IS_STATIC_MODULE('vfs_vfsx'),
                 enabled=bld.SAMBA3_IS_ENABLED_MODULE('vfs_vfsx'))
